### PR TITLE
adhere to csharp naming convention

### PR DESCRIPTION
**Pull request by mwiesenbauer**

### CODE REVIEW

**Comment by mwiesenbauer** [comment]
@rquackenbush can you please review my MR?

**Comment by Lj-dog** [comment]
Cshrop newuser.May I ask,where the rule come from?

**Comment by rquackenbush** [comment]
I’ve been pondering this. There seems to be some disagreement in the
community about how fields should be named. For example, in my day job,
we’ve adopted the “underscoreless” style.

I see where the c# guidelines still specify the underscore, but the tooling
in Visual Studio auto generates fields without them.

In general, I value consistency over specific style. And given the divide
in the community over which is preferred, I elect to keep what we have in
this case.

**Comment by mwiesenbauer** [comment]
@Lj-dog 
https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions
https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names

The editorconfig file should be based on https://github.com/dotnet/runtime/blob/main/.editorconfig.

@rquackenbush
Fine by me, closing the PR.

**Pull request closed without merging**
